-- Create additional DB users
CREATE USER :PG_WRITE_USER WITH PASSWORD :'PG_WRITE_PASSWORD';
CREATE USER :PG_READ_USER WITH PASSWORD :'PG_READ_PASSWORD';

-- Revoke some default privileges
REVOKE TEMPORARY ON DATABASE :PG_DATABASE FROM PUBLIC;
REVOKE CREATE ON SCHEMA public FROM PUBLIC;